extraction:
  cpp:
    after_prepare: 
      - python report.py 115
  cobol:
    after_prepare: 
      - python report.py 115
  csharp:
    after_prepare: 
      - python report.py 115
  java:
    after_prepare: 
      - python report.py 115
  javascript:
    after_prepare: 
      - python report.py 115
  python:
    after_prepare: 
      - python report.py 115
